# Generated by Django 4.0.5 on 2022-06-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('Issue_No', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Issue_No')),
                ('Name', models.CharField(max_length=200)),
                ('Job_No', models.CharField(max_length=200)),
                ('Vessel', models.CharField(max_length=20)),
                ('Port_Name', models.CharField(max_length=200)),
                ('Equipment', models.CharField(max_length=200)),
                ('Issue_Date', models.CharField(max_length=10)),
            ],
        ),
    ]
