# Generated by Django 4.0.5 on 2022-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('Barcode_No', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Item_No', models.CharField(max_length=20)),
            ],
        ),
    ]
